name: "Github Actions Simple Coverage"
description: "Determine if a job/step should pass based on coverage data from lcov file"
inputs:
  lcov-file-path: # id of input
    description: "path to lcov file"
    required: true
    default: "./lcov.info"
  fail-if-below:
    description: "coverage percentage to trigger failure"
    required: true
    default: 100
outputs:
  coverage-percent: # id of output
    description: "result of coverage based on the fail-at value"
runs:
  using: "node16"
  main: "src/index.js"
